# https://starship.rs/config

add_newline = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$package\
$fill\
$all\
$jobs\
$cmd_duration\
$line_break\
$character
"""

# Left side
[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[username]
style_user = "bold #B93835"
format = "[$user]($style) "

[hostname]
format = "on [$hostname]($style) in "

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"
read_only_style = "197"
read_only = "  "
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
style = "bold yellow"
format = "[$symbol$branch]($style) "

[git_status]
disabled = true

# Right side
[package]
style = "purple"
format = "[$version]($style) "

[jobs]
symbol = " "
style = "#828997"
number_threshold = 1
format = "[$symbol]($style) "

[cmd_duration]
min_time = 1000
format = "[$duration](#828997) "

# Language overrides
[c]
symbol = " "
style = "bold blue"
format = "[$symbol]($style) "

[cpp]
symbol = "󰙲 "
style = "bold blue"
format = "[$symbol]($style) "
disabled = false

[python]
symbol = " "
style = "bold #ffde57"
format = "[$symbol]($style) "

[rust]
symbol = " "
style = "bold #D34516"
format = "[$symbol]($style) "

[java]
symbol = " "
style = "bold #ED8B00"
format = "[$symbol]($style) "
